### PR TITLE
Improve diff editor

### LINKED ISSUE #21: File compares / diffs very hard to read
Hi again! 👋 

When I'm comparing files or performing diffs in vscode with the serendipity midnight theme, I get a border around each line which was changed (and even borders around individual parts of a line). This makes comparisons/diffs incredibly noisy and hard to read - and is everything but minimal 😉 . I can provide a screenshot for you if you like (currently working on proprietary code while writing this).

You can compare with a regular diff in GitHub which only has a red/green background color (no border around each and every changed line) which looks a lot cleaner (but using a less compelling theme).

I think an improvement would be to leave the background color as-is for the code that changed, but remove the borders. What do you think?

### PR DESCRIPTION
**Pull request by Chaphasilor**
- this fixes #21

### CODE REVIEW

**Comment by Chaphasilor** [comment]
Old:
image

New:
image

**Comment by michael-andreuzza** [comment]
Amazing, good one Fabi 💪.

**Comment by michael-andreuzza** [comment]
Good one Fabi.

**Comment by fredrikaverpil** [comment]
Thanks for such as swift fix! ⭐

**Comment by Chaphasilor** [comment]
Should be up now! Thanks for the reminder :)

**Pull request merged**
